---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: image-update
  namespace: sashimi
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: flux@sambunhi.nycu.one
        name: Flux image automation
      messageTemplate: >
        'apps: sashimi: {{range .Updated.Images}}{{.Repository}}:{{.Identifier}} {{end}}'
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  update:
    path: apps/sashimi
    strategy: Setters

