---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: image-update
  namespace: sashimi
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: ' '
        name: Flux-image-update
      messageTemplate: 'apps: sambunhi: {{range .Updated.Images}}{{.}}{{end}}'
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  update:
    path: apps/sashimi
    strategy: Setters

