apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sashimi
commonLabels:
  app: sashimi
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - fpm-repo.yaml
  - fpm-policy.yaml
  - nginx-repo.yaml
  - nginx-policy.yaml
  - image-update.yaml
images:
  - name: ghcr.io/sambunhi/sashimi/fpm
    newTag: sha-82812b6-25 # {"$imagepolicy": "sashimi:fpm:tag"}
  - name: ghcr.io/sambunhi/sashimi/nginx
    newTag: sha-82812b6-25 # {"$imagepolicy": "sashimi:nginx:tag"}
