apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sashimi
commonLabels:
  app: sashimi
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- fpm-repo.yaml
- fpm-policy.yaml
- nginx-repo.yaml
- nginx-policy.yaml
- image-update.yaml
- webhook.yaml
images:
- name: ghcr.io/sambunhi/sashimi/fpm
  newTag: sha-90a00dd-61 # {"$imagepolicy": "sashimi:fpm:tag"}
- name: ghcr.io/sambunhi/sashimi/nginx
  newTag: sha-7f82a14-62 # {"$imagepolicy": "sashimi:nginx:tag"}
