---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: matrix
  namespace: flux-system
spec:
  channel: '#cloudnative:xdavidwu.link'
  secretRef:
    name: matrix
  type: matrix

