---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Receiver
metadata:
  name: sambunhi-github
  namespace: flux-system
spec:
  events:
  - ping
  - push
  resources:
  - kind: GitRepository
    name: flux-system
  - kind: GitRepository
    name: sambunhi-infra-https
  secretRef:
    name: github-webhook-token
  type: github

