apiVersion: batch/v1
kind: CronJob
metadata:
  name: google-news-crawler
spec:
  jobTemplate:
    metadata:
      name: google-news-crawler
    spec:
      template:
        spec:
          containers:
            - image: ghcr.io/sambunhi/google_news_crawler:latest
              name: google-news-crawler
              env:
                - name: CRAWLER_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: env
                      key: CRAWLER_TOKEN
          restartPolicy: OnFailure
  schedule: 0 * * * *
