---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: google-news-crawler
  namespace: crawler
spec:
  image: ghcr.io/sambunhi/google_news_crawler
  interval: 1h0m0s

