---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: google-news-crawler
  namespace: crawler
spec:
  filterTags:
    extract: $number
    pattern: ^sha-[a-fA-F0-9]+-(?P<number>[1-9][0-9]*)$
  imageRepositoryRef:
    name: google-news-crawler
  policy:
    numerical:
      order: asc

