apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crawler
resources:
- namespace.yaml
- google-news-crawler.yaml
- rss-crawler.yaml
- tokenizer.yaml
images:
- name: ghcr.io/sambunhi/google_news_crawler
  newTag: sha-64463c0-12
- name: ghcr.io/sambunhi/rss_crawler
  newTag: sha-c05a846-13
- name: ghcr.io/sambunhi/tokenizer
  newTag: sha-c05a846-13
