apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crawler
resources:
- namespace.yaml
- google-news-crawler.yaml
images:
- name: ghcr.io/sambunhi/google_news_crawler
  newTag: sha-64463c0-12

