apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crawler
resources:
- namespace.yaml
- google-news-crawler.yaml
- rss-crawler.yaml
- tokenizer.yaml
- google-news-crawler-repo.yaml
- rss-crawler-repo.yaml
- tokenizer-repo.yaml
- google-news-crawler-policy.yaml
- rss-crawler-policy.yaml
- tokenizer-policy.yaml
- image-update.yaml
- webhook.yaml
images:
- name: ghcr.io/sambunhi/google_news_crawler
  newTag: sha-3013973-18 # {"$imagepolicy": "crawler:google-news-crawler:tag"}
- name: ghcr.io/sambunhi/rss_crawler
  newTag: sha-3013973-18 # {"$imagepolicy": "crawler:rss-crawler:tag"}
- name: ghcr.io/sambunhi/tokenizer
  newTag: sha-3013973-18 # {"$imagepolicy": "crawler:tokenizer:tag"}
