---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: flux-system
spec:
  chart:
    spec:
      chart: redis
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: redis
  values:
    auth:
      existingSecret: redis
      existingSecretPasswordKey: password
    metrics:
      enabled: true
