---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb-galera
  namespace: flux-system
spec:
  chart:
    spec:
      chart: mariadb-galera
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: mariadb-galera
  values:
    existingSecret: mariadb-galera
    metrics:
      enabled: true
      extraFlags:
        - --collect.info_schema.processlist
