apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: prometheus-rules
    namespace: monitoring
    files:
      - redis_exporter.yaml=../../dashboard-prebuilts/redis_exporter/rules.yaml
      - mysqld_exporter.yaml=../../dashboard-prebuilts/mysqld_exporter/rules.yaml
      - node_exporter.yaml=../../dashboard-prebuilts/node_exporter/node_rules.yaml
  - name: flux-dashboards
    namespace: monitoring
    files:
      - ../../external/flux/manifests/monitoring/monitoring-config/dashboards/cluster.json
      - ../../external/flux/manifests/monitoring/monitoring-config/dashboards/control-plane.json
  - name: node-dashboards
    namespace: monitoring
    files:
      - ../../dashboard-prebuilts/node_exporter/node-cluster-rsrc-use.json
      - ../../dashboard-prebuilts/node_exporter/node-rsrc-use.json
      - ../../dashboard-prebuilts/node_exporter/nodes.json
  - name: prometheus-dashboards
    namespace: monitoring
    files:
      - ../../dashboard-prebuilts/prometheus/prometheus.json
  - name: mariadb-dashboards
    namespace: monitoring
    files:
      - ../../dashboard-prebuilts/mysqld_exporter/mysql-overview.json
  - name: redis-dashboards
    namespace: monitoring
    files:
      - ../../dashboard-prebuilts/redis_exporter/redis-overview.json
