apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
configMapGenerator:
  - name: grafana-dashboards
    namespace: monitoring
    options:
      disableNameSuffixHash: true
    files:
      - ../../external/flux/manifests/monitoring/monitoring-config/dashboards/cluster.json
      - ../../external/flux/manifests/monitoring/monitoring-config/dashboards/control-plane.json
