apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - release.yaml
configMapGenerator:
  - name: grafana-dashboards
    files:
      - flux-cluster.json
      - flux-control-plane.json
