apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: flux-dashboards
    namespace: monitoring
    files:
      - ../../external/flux/manifests/monitoring/monitoring-config/dashboards/cluster.json
      - ../../external/flux/manifests/monitoring/monitoring-config/dashboards/control-plane.json
