---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: flux-system
spec:
  chart:
    spec:
      chart: loki-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: monitoring
  values:
    grafana:
      enabled: true
    prometheus:
      enabled: true

