---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: flux-system
spec:
  chart:
    spec:
      chart: loki-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: monitoring
  values:
    grafana:
      ingress:
        enabled: true
        hosts:
          - grafana.sambunhi.nycu.one
      enabled: true
      grafana.ini:
        server:
          root_url: https://grafana.sambunhi.nycu.one/
        auth.github:
          enabled: true
          allow_sign_up: true
          scopes: user:email,read:org
          auth_url: https://github.com/login/oauth/authorize
          token_url: https://github.com/login/oauth/access_token
          api_url: https://api.github.com/user
          allowed_organizations: sambunhi
          client_id: e6476d3efb874b345cc4
      envFromSecrets:
        - name: grafana-envs
      sidecar:
        datasources:
          enabled: false
      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
          - name: Loki
            type: loki
            access: proxy
            url: http://monitoring-loki-stack:3100
            version: 1
            isDefault: true
            jsonData:
              maxLines: 1000
          - name: Prometheus
            type: prometheus
            access: proxy
            url: http://monitoring-loki-stack-prometheus-server:80
            version: 1
            isDefault: false
            jsonData:
              timeInterval: 30s
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
            - name: 'flux'
              orgId: 1
              folder: 'Flux'
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/flux
            - name: 'node'
              orgId: 1
              folder: 'Node Exporter'
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/node
            - name: 'prometheus'
              orgId: 1
              folder: 'Prometheus'
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/prometheus
            - name: 'mariadb'
              orgId: 1
              folder: 'MariaDB'
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/mariadb
      dashboardsConfigMaps:
        flux: flux-dashboards
        node: node-dashboards
        prometheus: prometheus-dashboards
        mariadb: mariadb-dashboards
    prometheus:
      enabled: true
      server:
        global:
          scrape_interval: 30s

