---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: flux-system
spec:
  chart:
    spec:
      chart: loki-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
  install:
    createNamespace: true
  interval: 10m0s
  targetNamespace: monitoring
  values:
    grafana:
      ingress:
        enabled: true
        hosts:
          - grafana.sambunhi.nycu.one
      enabled: true
      grafana.ini:
        server:
          root_url: https://grafana.sambunhi.nycu.one/
        users:
          viewers_can_edit: true
        auth.github:
          enabled: true
          allow_sign_up: true
          scopes: user:email,read:org
          auth_url: https://github.com/login/oauth/authorize
          token_url: https://github.com/login/oauth/access_token
          api_url: https://api.github.com/user
          allowed_organizations: sambunhi
          client_id: e6476d3efb874b345cc4
      envFromSecrets:
        - name: grafana-envs
      sidecar:
        datasources:
          enabled: false
      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
          - name: Loki
            type: loki
            access: proxy
            url: http://monitoring-loki-stack:3100
            version: 1
            isDefault: false
            jsonData:
              maxLines: 1000
          - name: Prometheus
            type: prometheus
            access: proxy
            url: http://monitoring-loki-stack-prometheus-server:80
            version: 1
            isDefault: true
            jsonData:
              timeInterval: 30s
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
            - name: 'flux'
              orgId: 1
              folder: 'Flux'
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/flux
            - name: 'node'
              orgId: 1
              folder: 'Node Exporter'
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/node
            - name: 'prometheus'
              orgId: 1
              folder: 'Prometheus'
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/prometheus
            - name: 'mariadb'
              orgId: 1
              folder: 'MariaDB'
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/mariadb
            - name: 'redis'
              orgId: 1
              folder: 'Redis'
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/redis
            - name: 'traefik-dashboards'
              orgId: 1
              folder: 'Traefik proxy'
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/traefik
            - name: 'kubernetes'
              orgId: 1
              folder: 'Kubernetes'
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/kubernetes
      dashboardsConfigMaps:
        flux: flux-dashboards
        node: node-dashboards
        prometheus: prometheus-dashboards
        mariadb: mariadb-dashboards
        redis: redis-dashboards
        traefik: traefik-dashboards
        kubernetes: kubernetes-dashboards
    prometheus:
      enabled: true
      kube-state-metrics:
        prometheusScrape: false
      extraScrapeConfigs: |
        - job_name: kube-state-metrics
          static_configs:
            - targets:
              - monitoring-loki-stack-kube-state-metrics:8080
      server:
        global:
          scrape_interval: 30s
        extraConfigmapMounts:
          - name: recording-rules
            mountPath: /etc/config/recording.d
            subPath: ""
            configMap: prometheus-rules
            readOnly: true
          - name: alert-rules
            mountPath: /etc/config/alerts.d
            subPath: ""
            configMap: prometheus-alerts
            readOnly: true
        strategy:
          type: Recreate
      serverFiles:
        prometheus.yml:
          rule_files:
            - /etc/config/recording.d/*.yaml
            - /etc/config/alerts.d/*.yaml
      alertmanager:
        extraSecretMounts:
          - name: matrix-webhook
            mountPath: /etc/matrix-webhook
            subPath: url
            secretName: matrix-webhook-url
            readOnly: true
        strategy:
          type: Recreate
      alertmanagerFiles:
        alertmanager.yml:
          receivers:
            - name: default-receiver
              slack_configs:
                - api_url_file: /etc/matrix-webhook
                  send_resolved: true
